site_name: Siddhi-IO-HTTP
extra_css:
- stylesheets/extra.css
extra_javascript:
- javascripts/extra.js
site_favicon: images/favicon.ico
extra:
  logo: images/siddhi-logo-w.svg
  palette:
    primary: teal
    accent: teal
google_analytics:
- UA-103065-28
- auto
pages:
- Welcome to WSO2 Siddhi IO HTTP: index.md
- API Docs:
  - 1.0.11: api/1.0.11.md
  - 1.0.10: api/1.0.10.md
  - 1.0.4: api/1.0.4.md
  - latest: api/latest.md
- License: license.md
theme: material
